// GENERATED by scripts/economy/calibrate.ts --empires — do not edit by hand; rerun
// it (`npx tsx scripts/economy/calibrate.ts --empires`) after changing the empires'
// seed (economy/empireSeed.ts, the generated galaxy) or the tick.
import type { SeedCalibration } from './seedCalibration'

// Per empire world: the prices and wages its markets settle at.
export const EMPIRE_WORLD_CALIBRATION: SeedCalibration = {

}

// Per empire: the starting tax rate that opens its budget near balance.
export const EMPIRE_TAX_RATES: Record<string, number> = {

}
