// GENERATED by scripts/economy/calibrate.ts — do not edit by hand; rerun it
// (`npx tsx scripts/economy/calibrate.ts`) after changing the seed or the tick.
import type { GoodId } from './goods'
import type { PopClass } from './recipes'

// Per world: the prices and wages its markets settle at.
export interface WorldCalibration {
  prices?: Partial<Record<GoodId, number>>
  wages?: Partial<Record<PopClass, number>>
}
export type SeedCalibration = Record<string, WorldCalibration>

export const SEED_CALIBRATION: SeedCalibration = {
  "Arcadia": {
    prices: { electricity: 2.422, ironOre: 1.2, coal: 1.316, oil: 5.031, rareMetals: 16.1, timber: 1.2, phosphate: 4.024, sulfur: 4.024, hardwood: 5.031, grains: 2.08, livestock: 2.4, sugar: 1.2, coffee: 3.2, tea: 2.8, meat: 2.8, fish: 2.4, steel: 7.941, concrete: 1.2, lumber: 2, fuel: 11.36, chemicals: 7.043, fertilizer: 6.037, explosives: 10.06, semiconductors: 22.13, dyes: 12.07, glass: 10.06, paper: 10.57, tools: 3.6, machinery: 6, heavyMachinery: 26.16, electricalMachinery: 20.12, precisionMachinery: 34.21, electronics: 24.04, engines: 20.12, automobiles: 40.09, locomotives: 70.43, aircraft: 125.4, oceanGoingShips: 161, spaceships: 452.7, rockets: 201.2, groceries: 1.6, consumerGoods: 7.352, furniture: 18.67, luxuryGoods: 29.77, art: 26.92, healthcare: 8.238, dental: 4, education: 48.81, retail: 2.8, onlineServices: 11.09, infrastructure: 3.214 },
    wages: { subsistence: 5.183, labor: 10.37, technical: 15.55, professional: 25.92, investor: 31.1, political: 31.1 },
  },
  "Lalande 21185 d": {
    prices: { electricity: 2.35, ironOre: 1.2, coal: 2.122, oil: 5.117, rareMetals: 16.37, timber: 3.07, phosphate: 1.6, sulfur: 4.093, hardwood: 5.117, grains: 1.897, livestock: 2.4, sugar: 3.07, coffee: 8.186, tea: 7.163, meat: 2.8, fish: 5.347, steel: 11.05, concrete: 1.2, lumber: 5.117, fuel: 27.96, chemicals: 10.87, fertilizer: 2.4, explosives: 10.23, semiconductors: 22.51, dyes: 12.28, glass: 10.23, paper: 13.52, tools: 3.6, machinery: 6, heavyMachinery: 26.61, electricalMachinery: 20.47, precisionMachinery: 34.79, electronics: 18.42, engines: 20.47, automobiles: 45.24, locomotives: 71.63, aircraft: 112.6, oceanGoingShips: 163.7, spaceships: 460.5, rockets: 204.7, groceries: 1.6, consumerGoods: 8.874, furniture: 21.75, luxuryGoods: 36.8, art: 33.43, healthcare: 10.68, dental: 4, education: 11.03, retail: 2.8, onlineServices: 9.21, infrastructure: 8.908 },
    wages: { subsistence: 6.159, labor: 16.58, technical: 24.88, professional: 43.43, investor: 36.95, political: 50.44 },
  },
  "Luna": {
    prices: { electricity: 4.293, ironOre: 1.2, coal: 0.8, oil: 5.184, rareMetals: 16.59, timber: 3.11, phosphate: 4.147, sulfur: 4.147, hardwood: 5.184, grains: 2.189, livestock: 6.412, sugar: 3.11, coffee: 8.294, tea: 7.257, meat: 2.8, fish: 2.4, steel: 7.059, concrete: 3.561, lumber: 5.935, fuel: 10.41, chemicals: 7.257, fertilizer: 6.22, explosives: 10.37, semiconductors: 22.81, dyes: 12.44, glass: 13.63, paper: 11.72, tools: 3.6, machinery: 6, heavyMachinery: 26.95, electricalMachinery: 20.73, precisionMachinery: 35.25, electronics: 25.98, engines: 20.73, automobiles: 46.28, locomotives: 72.57, aircraft: 137.5, oceanGoingShips: 165.9, spaceships: 466.5, rockets: 207.3, groceries: 1.6, consumerGoods: 5.089, furniture: 17.38, luxuryGoods: 35.53, art: 27.42, healthcare: 11.38, dental: 4, education: 27.66, retail: 2.8, onlineServices: 12.67, infrastructure: 3.218 },
    wages: { subsistence: 7.219, labor: 14.44, technical: 21.66, professional: 36.1, investor: 43.32, political: 43.32 },
  },
  "Mars": {
    prices: { electricity: 2.513, ironOre: 2.035, coal: 1.644, oil: 2, rareMetals: 9.361, timber: 1.694, phosphate: 2.241, sulfur: 1.6, hardwood: 2.116, grains: 0.8052, livestock: 2.4, sugar: 3.11, coffee: 8.294, tea: 7.257, meat: 7.337, fish: 3.661, steel: 7.441, concrete: 1.2, lumber: 2.163, fuel: 5.584, chemicals: 2.812, fertilizer: 2.4, explosives: 112.9, semiconductors: 9.035, dyes: 4.8, glass: 4, paper: 3.6, tools: 5.022, machinery: 11.45, heavyMachinery: 10.4, electricalMachinery: 8, precisionMachinery: 13.6, electronics: 7.274, engines: 22.78, automobiles: 12.8, locomotives: 28, aircraft: 44, oceanGoingShips: 64, spaceships: 180, rockets: 80, groceries: 1.711, consumerGoods: 5.841, furniture: 9.738, luxuryGoods: 10.4, art: 28.28, healthcare: 13.93, dental: 10.49, education: 12.06, retail: 3.235, onlineServices: 12.77, infrastructure: 3.2 },
    wages: { subsistence: 5.006, labor: 12.58, technical: 19.06, professional: 31.43, investor: 29.44, political: 37.73 },
  },
  "Proxima b": {
    prices: { electricity: 4.172, ironOre: 1.2, coal: 0.8, oil: 5.031, rareMetals: 16.1, timber: 3.018, phosphate: 4.024, sulfur: 4.024, hardwood: 5.031, grains: 2.246, livestock: 6.212, sugar: 3.018, coffee: 8.049, tea: 7.043, meat: 2.8, fish: 2.4, steel: 6.84, concrete: 3.018, lumber: 5.031, fuel: 18.78, chemicals: 7.043, fertilizer: 6.037, explosives: 10.06, semiconductors: 22.13, dyes: 12.07, glass: 10.06, paper: 10.74, tools: 3.6, machinery: 6, heavyMachinery: 26.16, electricalMachinery: 20.12, precisionMachinery: 34.21, electronics: 24.85, engines: 20.12, automobiles: 41.47, locomotives: 70.43, aircraft: 116.5, oceanGoingShips: 161, spaceships: 452.7, rockets: 201.2, groceries: 1.6, consumerGoods: 5.747, furniture: 19.05, luxuryGoods: 31.98, art: 25.65, healthcare: 8.196, dental: 4, education: 100.6, retail: 2.801, onlineServices: 12.49, infrastructure: 5.489 },
    wages: { subsistence: 19.25, labor: 38.5, technical: 57.75, professional: 96.26, investor: 115.5, political: 115.5 },
  },
  "Venus": {
    prices: { electricity: 3.614, ironOre: 1.2, coal: 1.378, oil: 2, rareMetals: 16.35, timber: 3.065, phosphate: 4.087, sulfur: 4.087, hardwood: 5.848, grains: 1.56, livestock: 2.4, sugar: 3.065, coffee: 8.173, tea: 7.152, meat: 2.8, fish: 2.4, steel: 8.97, concrete: 1.2, lumber: 5.848, fuel: 9.159, chemicals: 2.8, fertilizer: 6.13, explosives: 10.22, semiconductors: 22.48, dyes: 12.26, glass: 10.22, paper: 10.15, tools: 3.6, machinery: 6, heavyMachinery: 26.56, electricalMachinery: 20.43, precisionMachinery: 34.74, electronics: 21.09, engines: 20.43, automobiles: 36.1, locomotives: 71.52, aircraft: 128.1, oceanGoingShips: 163.5, spaceships: 459.8, rockets: 204.3, groceries: 1.6, consumerGoods: 6.622, furniture: 5.6, luxuryGoods: 31.16, art: 8.8, healthcare: 9.372, dental: 4, education: 10.45, retail: 2.8, onlineServices: 3.6, infrastructure: 6.882 },
    wages: { subsistence: 5.028, labor: 13.3, technical: 20.19, professional: 34.19, investor: 29.98, political: 39.97 },
  },
}

// Per nation: the starting tax rate that opens its budget near balance.
export interface CountryCalibration {
  taxRate?: number
}
export const COUNTRY_CALIBRATION: Record<string, CountryCalibration> = {
  "imperial-state-of-mars": { taxRate: 0.12 },
  "kingdom-of-lalande": { taxRate: 0.1 },
  "orion-republic": { taxRate: 0.08 },
  "republic-of-venus": { taxRate: 0.1 },
}
