// GENERATED by scripts/economy/calibrate.ts — do not edit by hand; rerun it
// (`npx tsx scripts/economy/calibrate.ts`) after changing the seed or the tick.
import type { GoodId } from './goods'
import type { PopClass } from './recipes'

// Per world: the prices and wages its markets settle at.
export interface WorldCalibration {
  prices?: Partial<Record<GoodId, number>>
  wages?: Partial<Record<PopClass, number>>
}
export type SeedCalibration = Record<string, WorldCalibration>

export const SEED_CALIBRATION: SeedCalibration = {
  "Arcadia": {
    prices: { electricity: 4.591, ironOre: 1.2, coal: 1.422, oil: 3.35, rareMetals: 6.4, timber: 1.2, phosphate: 1.6, sulfur: 1.6, hardwood: 2, grains: 2.025, livestock: 2.406, sugar: 1.2, coffee: 3.2, tea: 2.8, meat: 7.163, fish: 4.529, steel: 8.901, concrete: 1.2, lumber: 2, fuel: 4.046, chemicals: 2.8, fertilizer: 6.101, explosives: 4, semiconductors: 8.8, dyes: 4.8, glass: 4, paper: 3.973, tools: 3.6, machinery: 6, heavyMachinery: 10.4, electricalMachinery: 8, precisionMachinery: 13.6, electronics: 7.2, engines: 8, automobiles: 71.58, locomotives: 71.18, aircraft: 44, oceanGoingShips: 64, spaceships: 180, rockets: 80, groceries: 1.6, consumerGoods: 9.364, furniture: 18.76, textiles: 2, luxuryGoods: 38.51, art: 27.24, healthcare: 16.42, dental: 4, education: 8.895, retail: 3.18, onlineServices: 49.25, transportation: 4.657 },
    wages: { subsistence: 5, labor: 9.081, technical: 13.73, professional: 23.64, investor: 26.81, political: 28.41 },
  },
  "Earth": {
    prices: { electricity: 4.603, ironOre: 2.623, coal: 2.355, oil: 6.48, rareMetals: 6.4, timber: 1.2, phosphate: 1.6, sulfur: 1.6, hardwood: 2, grains: 1.261, livestock: 2.417, sugar: 3.567, coffee: 9.511, tea: 8.322, meat: 8.376, fish: 3.257, steel: 7.718, concrete: 1.2, lumber: 2, fuel: 11.09, chemicals: 2.832, fertilizer: 2.4, explosives: 4, semiconductors: 8.8, dyes: 4.8, glass: 4, paper: 8.442, tools: 6.077, machinery: 6.067, heavyMachinery: 10.4, electricalMachinery: 8, precisionMachinery: 13.6, electronics: 7.2, engines: 8, automobiles: 54.33, locomotives: 28, aircraft: 44, oceanGoingShips: 64, spaceships: 180, rockets: 80, groceries: 1.625, consumerGoods: 7.716, furniture: 65.9, textiles: 2.026, luxuryGoods: 50.31, art: 33.46, healthcare: 10.94, dental: 4, education: 11.09, retail: 3.04, onlineServices: 30.13, transportation: 3.2 },
    wages: { subsistence: 5.801, labor: 15.44, technical: 23.66, professional: 39.71, investor: 34.59, political: 46.07 },
  },
  "Lalande 21185 d": {
    prices: { electricity: 4.097, ironOre: 3.218, coal: 2.071, oil: 5.672, rareMetals: 6.4, timber: 1.2, phosphate: 1.6, sulfur: 1.6, hardwood: 2, grains: 1.199, livestock: 2.4, sugar: 3.088, coffee: 8.236, tea: 7.206, meat: 2.8, fish: 5.751, steel: 8.443, concrete: 1.2, lumber: 2, fuel: 7.074, chemicals: 2.8, fertilizer: 2.4, explosives: 4, semiconductors: 8.8, dyes: 4.8, glass: 4, paper: 5.45, tools: 3.6, machinery: 6, heavyMachinery: 10.4, electricalMachinery: 8, precisionMachinery: 13.6, electronics: 7.2, engines: 8, automobiles: 80.97, locomotives: 72.06, aircraft: 44, oceanGoingShips: 64, spaceships: 180, rockets: 80, groceries: 1.6, consumerGoods: 8.4, furniture: 23.95, textiles: 2.012, luxuryGoods: 49.47, art: 33.27, healthcare: 11.39, dental: 4, education: 12.59, retail: 4.231, onlineServices: 9.265, transportation: 3.21 },
    wages: { subsistence: 5.013, labor: 13.46, technical: 20.56, professional: 34.82, investor: 29.33, political: 40.26 },
  },
  "Luna": {
    prices: { electricity: 4.521, ironOre: 1.2, coal: 0.8, oil: 5.132, rareMetals: 16.42, timber: 3.079, phosphate: 4.105, sulfur: 4.105, hardwood: 5.132, grains: 1.091, livestock: 5.311, sugar: 3.079, coffee: 8.211, tea: 7.184, meat: 2.8, fish: 2.4, steel: 5.678, concrete: 3.525, lumber: 5.875, fuel: 10.05, chemicals: 7.184, fertilizer: 6.158, explosives: 10.26, semiconductors: 22.58, dyes: 12.32, glass: 11.75, paper: 10.34, tools: 3.6, machinery: 6, heavyMachinery: 26.68, electricalMachinery: 20.53, precisionMachinery: 34.89, electronics: 21.88, engines: 20.53, automobiles: 43.68, locomotives: 71.84, aircraft: 133.3, oceanGoingShips: 164.2, spaceships: 478.9, rockets: 239.7, groceries: 1.6, consumerGoods: 5.349, furniture: 17.2, textiles: 5.998, luxuryGoods: 34.83, art: 28.74, healthcare: 10.96, dental: 4, education: 29.35, retail: 2.873, onlineServices: 47.65, transportation: 3.2 },
    wages: { subsistence: 6.018, labor: 12.04, technical: 18.05, professional: 30.09, investor: 36.11, political: 37.85 },
  },
  "Mars": {
    prices: { electricity: 3.87, ironOre: 2.112, coal: 1.476, oil: 3.627, rareMetals: 6.4, timber: 1.2, phosphate: 1.6, sulfur: 1.6, hardwood: 2, grains: 0.8, livestock: 2.541, sugar: 3.079, coffee: 8.211, tea: 7.184, meat: 6.132, fish: 3.77, steel: 5.908, concrete: 1.2, lumber: 3.339, fuel: 8.191, chemicals: 2.8, fertilizer: 2.4, explosives: 4, semiconductors: 8.8, dyes: 4.8, glass: 4, paper: 6.137, tools: 4.539, machinery: 8.49, heavyMachinery: 10.4, electricalMachinery: 8, precisionMachinery: 13.6, electronics: 7.2, engines: 8, automobiles: 13.19, locomotives: 28, aircraft: 44, oceanGoingShips: 64, spaceships: 201.4, rockets: 80, groceries: 1.734, consumerGoods: 5.91, furniture: 12.79, textiles: 2.79, luxuryGoods: 10.51, art: 29.79, healthcare: 15.65, dental: 9.017, education: 11.48, retail: 3.815, onlineServices: 21.67, transportation: 3.2 },
    wages: { subsistence: 5.853, labor: 15.53, technical: 24.36, professional: 40.58, investor: 35.05, political: 47.37 },
  },
  "Proxima b": {
    prices: { electricity: 5.092, ironOre: 1.2, coal: 0.8, oil: 5.084, rareMetals: 16.27, timber: 3.051, phosphate: 4.068, sulfur: 4.068, hardwood: 5.084, grains: 2.002, livestock: 5.186, sugar: 3.051, coffee: 8.135, tea: 7.118, meat: 2.8, fish: 2.4, steel: 8.156, concrete: 3.264, lumber: 5.44, fuel: 9.739, chemicals: 7.118, fertilizer: 6.101, explosives: 10.17, semiconductors: 22.37, dyes: 12.2, glass: 10.88, paper: 10.94, tools: 3.6, machinery: 6, heavyMachinery: 26.44, electricalMachinery: 20.34, precisionMachinery: 34.57, electronics: 21.93, engines: 20.34, automobiles: 77.81, locomotives: 71.18, aircraft: 134.8, oceanGoingShips: 189.2, spaceships: 465.4, rockets: 223.7, groceries: 1.6, consumerGoods: 5.797, furniture: 19.97, textiles: 5.994, luxuryGoods: 42.43, art: 26.2, healthcare: 12.81, dental: 4, education: 14.85, retail: 3.206, onlineServices: 49.73, transportation: 3.2 },
    wages: { subsistence: 13.98, labor: 27.95, technical: 41.93, professional: 69.88, investor: 83.85, political: 83.85 },
  },
  "Venus": {
    prices: { electricity: 3.395, ironOre: 2.029, coal: 1.291, oil: 5.323, rareMetals: 6.4, timber: 1.2, phosphate: 1.6, sulfur: 1.6, hardwood: 2, grains: 1.193, livestock: 2.4, sugar: 3.07, coffee: 8.186, tea: 7.163, meat: 2.8, fish: 2.4, steel: 7.389, concrete: 1.2, lumber: 2, fuel: 6.29, chemicals: 2.8, fertilizer: 6.14, explosives: 4, semiconductors: 8.8, dyes: 4.8, glass: 4, paper: 6.849, tools: 3.6, machinery: 6, heavyMachinery: 10.4, electricalMachinery: 8, precisionMachinery: 13.6, electronics: 7.2, engines: 8, automobiles: 28.04, locomotives: 71.63, aircraft: 44, oceanGoingShips: 64, spaceships: 180.4, rockets: 80, groceries: 1.6, consumerGoods: 7.233, furniture: 10.09, textiles: 2, luxuryGoods: 28.31, art: 8.8, healthcare: 14.7, dental: 4, education: 14.61, retail: 5.172, onlineServices: 6.718, transportation: 3.998 },
    wages: { subsistence: 6.527, labor: 17.55, technical: 26.94, professional: 45.93, investor: 39.16, political: 53.39 },
  },
}

// Per nation: the starting tax rate that opens its budget near balance.
export interface CountryCalibration {
  taxRate?: number
}
export const COUNTRY_CALIBRATION: Record<string, CountryCalibration> = {
  "earth": { taxRate: 0.13 },
  "imperial-state-of-mars": { taxRate: 0.1 },
  "kingdom-of-lalande": { taxRate: 0.1 },
  "orion-republic": { taxRate: 0.06 },
  "republic-of-venus": { taxRate: 0.1 },
}
