// GENERATED by scripts/economy/calibrate.ts — do not edit by hand; rerun it
// (`npx tsx scripts/economy/calibrate.ts`) after changing the seed or the tick.
import type { GoodId } from './goods'
import type { PopClass } from './recipes'

// Per world: the prices and wages its markets settle at.
export interface WorldCalibration {
  prices?: Partial<Record<GoodId, number>>
  wages?: Partial<Record<PopClass, number>>
}
export type SeedCalibration = Record<string, WorldCalibration>

export const SEED_CALIBRATION: SeedCalibration = {
  "Arcadia": {
    prices: { electricity: 4.73, ironOre: 1.2, coal: 1.227, oil: 2.975, rareMetals: 6.4, timber: 1.2, phosphate: 1.6, sulfur: 1.6, hardwood: 2, grains: 2.022, livestock: 2.4, sugar: 1.2, coffee: 3.2, tea: 2.8, meat: 7.183, fish: 4.072, steel: 9.487, concrete: 1.2, lumber: 2, fuel: 3.2, chemicals: 2.8, fertilizer: 6.1, explosives: 4, semiconductors: 8.8, dyes: 4.8, glass: 4, paper: 4.238, tools: 3.6, machinery: 6, heavyMachinery: 10.4, electricalMachinery: 8, precisionMachinery: 13.6, electronics: 7.2, engines: 8, automobiles: 114.7, locomotives: 71.17, aircraft: 44, oceanGoingShips: 64, spaceships: 180, rockets: 80, groceries: 1.6, consumerGoods: 11.58, furniture: 20.12, textiles: 2, luxuryGoods: 37.57, art: 27.21, healthcare: 18.37, dental: 4, education: 8.267, retail: 3.238, onlineServices: 107.4, infrastructure: 4.517 },
    wages: { subsistence: 5.043, labor: 9.133, technical: 13.95, professional: 24.45, investor: 24.44, political: 29.4 },
  },
  "Lalande 21185 d": {
    prices: { electricity: 4.2, ironOre: 3.33, coal: 2.13, oil: 6.077, rareMetals: 6.4, timber: 1.2, phosphate: 1.6, sulfur: 1.6, hardwood: 2, grains: 1.045, livestock: 2.4, sugar: 3.176, coffee: 8.47, tea: 7.411, meat: 2.8, fish: 5.847, steel: 8.614, concrete: 1.2, lumber: 2, fuel: 5.957, chemicals: 2.8, fertilizer: 2.4, explosives: 4, semiconductors: 8.8, dyes: 4.8, glass: 4, paper: 5.753, tools: 3.6, machinery: 6, heavyMachinery: 10.4, electricalMachinery: 8, precisionMachinery: 13.6, electronics: 7.2, engines: 8, automobiles: 119.7, locomotives: 74.11, aircraft: 44, oceanGoingShips: 64, spaceships: 180, rockets: 80, groceries: 1.6, consumerGoods: 9.906, furniture: 29.76, textiles: 2.021, luxuryGoods: 51.19, art: 36.6, healthcare: 11.89, dental: 4, education: 13.11, retail: 4.329, onlineServices: 9.529, infrastructure: 3.274 },
    wages: { subsistence: 5.123, labor: 13.92, technical: 21.24, professional: 36.04, investor: 30.31, political: 41.67 },
  },
  "Luna": {
    prices: { electricity: 4.836, ironOre: 1.2, coal: 0.8, oil: 5.207, rareMetals: 16.66, timber: 3.124, phosphate: 4.165, sulfur: 4.165, hardwood: 5.207, grains: 0.9396, livestock: 4.536, sugar: 3.124, coffee: 8.331, tea: 7.29, meat: 2.8, fish: 2.4, steel: 5.534, concrete: 3.827, lumber: 6.379, fuel: 11.44, chemicals: 7.29, fertilizer: 6.248, explosives: 10.41, semiconductors: 22.91, dyes: 12.5, glass: 12.76, paper: 12.21, tools: 3.6, machinery: 6, heavyMachinery: 27.08, electricalMachinery: 20.83, precisionMachinery: 35.41, electronics: 24.1, engines: 20.83, automobiles: 53.45, locomotives: 72.9, aircraft: 147.1, oceanGoingShips: 166.6, spaceships: 495.3, rockets: 263.4, groceries: 1.6, consumerGoods: 5.027, furniture: 18.9, textiles: 12.21, luxuryGoods: 40.39, art: 30.85, healthcare: 10.44, dental: 4, education: 30.16, retail: 2.808, onlineServices: 108, infrastructure: 3.2 },
    wages: { subsistence: 5.485, labor: 10.97, technical: 16.46, professional: 27.43, investor: 32.91, political: 35.41 },
  },
  "Mars": {
    prices: { electricity: 3.999, ironOre: 1.83, coal: 1.109, oil: 3.27, rareMetals: 6.4, timber: 1.2, phosphate: 1.6, sulfur: 1.6, hardwood: 2, grains: 0.8, livestock: 2.401, sugar: 3.124, coffee: 8.331, tea: 7.29, meat: 4.819, fish: 3.227, steel: 5.591, concrete: 1.2, lumber: 2.294, fuel: 8.368, chemicals: 2.8, fertilizer: 2.4, explosives: 4, semiconductors: 8.8, dyes: 4.8, glass: 4, paper: 5.091, tools: 3.747, machinery: 7.036, heavyMachinery: 10.4, electricalMachinery: 8, precisionMachinery: 13.6, electronics: 7.2, engines: 8, automobiles: 12.98, locomotives: 28, aircraft: 44, oceanGoingShips: 64, spaceships: 180, rockets: 80, groceries: 1.6, consumerGoods: 6.085, furniture: 10.79, textiles: 2.962, luxuryGoods: 10.46, art: 32.54, healthcare: 21.19, dental: 6.942, education: 11.71, retail: 3.507, onlineServices: 59.64, infrastructure: 3.2 },
    wages: { subsistence: 5.648, labor: 15.31, technical: 23.95, professional: 39.65, investor: 33.84, political: 46.4 },
  },
  "Proxima b": {
    prices: { electricity: 5.892, ironOre: 1.2, coal: 0.8, oil: 5.083, rareMetals: 16.27, timber: 3.05, phosphate: 4.067, sulfur: 4.067, hardwood: 5.083, grains: 1.99, livestock: 4.973, sugar: 3.05, coffee: 8.134, tea: 7.117, meat: 2.8, fish: 2.4, steel: 8.037, concrete: 3.492, lumber: 5.82, fuel: 10.63, chemicals: 7.117, fertilizer: 6.1, explosives: 10.17, semiconductors: 22.37, dyes: 12.2, glass: 11.64, paper: 12.07, tools: 3.6, machinery: 6, heavyMachinery: 26.43, electricalMachinery: 20.33, precisionMachinery: 34.57, electronics: 23.92, engines: 20.33, automobiles: 147.9, locomotives: 71.17, aircraft: 147.8, oceanGoingShips: 204, spaceships: 469.3, rockets: 234.7, groceries: 1.6, consumerGoods: 5.67, furniture: 20.83, textiles: 6.711, luxuryGoods: 40.65, art: 26.34, healthcare: 13.43, dental: 4, education: 18.75, retail: 3.772, onlineServices: 108, infrastructure: 3.2 },
    wages: { subsistence: 12.74, labor: 25.48, technical: 38.22, professional: 63.7, investor: 76.44, political: 76.44 },
  },
  "Venus": {
    prices: { electricity: 3.442, ironOre: 1.748, coal: 1.026, oil: 5.432, rareMetals: 6.4, timber: 1.2, phosphate: 1.6, sulfur: 1.6, hardwood: 2, grains: 1.052, livestock: 2.4, sugar: 3.079, coffee: 8.211, tea: 7.185, meat: 2.8, fish: 2.4, steel: 6.686, concrete: 1.2, lumber: 2, fuel: 5.542, chemicals: 2.8, fertilizer: 6.159, explosives: 4, semiconductors: 8.8, dyes: 4.8, glass: 4, paper: 6.5, tools: 3.6, machinery: 6, heavyMachinery: 10.4, electricalMachinery: 8, precisionMachinery: 13.6, electronics: 7.2, engines: 8, automobiles: 33.07, locomotives: 71.85, aircraft: 44, oceanGoingShips: 64, spaceships: 180, rockets: 80, groceries: 1.6, consumerGoods: 7.414, furniture: 6.945, textiles: 2.008, luxuryGoods: 29.52, art: 8.8, healthcare: 14.3, dental: 4, education: 15.64, retail: 4.819, onlineServices: 5.679, infrastructure: 3.711 },
    wages: { subsistence: 6.236, labor: 16.91, technical: 25.87, professional: 44.33, investor: 37.42, political: 51.37 },
  },
}

// Per nation: the starting tax rate that opens its budget near balance.
export interface CountryCalibration {
  taxRate?: number
}
export const COUNTRY_CALIBRATION: Record<string, CountryCalibration> = {
  "imperial-state-of-mars": { taxRate: 0.12 },
  "kingdom-of-lalande": { taxRate: 0.1 },
  "orion-republic": { taxRate: 0.06 },
  "republic-of-venus": { taxRate: 0.09 },
}
